name: flutter_provider_example
description: Flutter provider example
version: 1.0.0+1
publish_to: none

environment:
  sdk: "<4.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_provider:
    path: ../
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_provider:
    path: ../

flutter:
  uses-material-design: true