name: flutter_provider_example
description: Flutter provider example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_provider:
    path: ../
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_provider:
    path: ../