name: flutter_provider
description: Flutter generic provider using InheritedWidget. An helper to easily exposes a value using InheritedWidget without having to write one.
version: 1.1.0+2
homepage: https://github.com/hoc081098/flutter_provider
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  test_api: ^0.2.2
  flutter_test:
    sdk: flutter

flutter: