name: flutter_provider
description: Flutter generic provider using InheritedWidget. An helper to easily exposes a value using InheritedWidget without having to write one.
version: 2.1.0
homepage: https://github.com/hoc081098/flutter_provider.git
repository: https://github.com/hoc081098/flutter_provider.git
issue_tracker: https://github.com/hoc081098/flutter_provider/issues

environment:
  sdk: '<4.0.0'
  flutter: '>=2.5.0'

dependencies:
  meta: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: