name: flutter_provider
description: Flutter generic provider using InheritedWidget. An helper to easily exposes a value using InheritedWidget without having to write one.
version: 2.0.0-nullsafety.0
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/flutter_provider.git
repository: https://github.com/hoc081098/flutter_provider.git
issue_tracker: https://github.com/hoc081098/flutter_provider/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.1.8
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  flutter_test:
    sdk: flutter

flutter: